// lib/recommendations.ts
// ============================================================
// Home maintenance action library — 12 months of recommendations
// filtered by feature toggles, climate zone, and system age
// ============================================================

export interface Recommendation {
  id: string;
  feature: FeatureKey;
  title: string;
  desc: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  category: string;       // maps to your existing task categories
  months: number[];        // 0-indexed (0 = Jan, 11 = Dec)
  recurring: string;       // display label
  recurrenceType: 'one_time' | 'monthly' | 'quarterly' | 'yearly' | 'custom';
  recurrenceDays?: number; // for 'custom' type
  timeEstMinutes: number;  // estimated time in minutes
  costEstLow: number;      // DIY cost
  costEstHigh: number;     // pro cost
  diyPro: 'DIY' | 'Pro' | 'Either';
  zones: string[] | 'all'; // climate zones this applies to
}

export type FeatureKey =
  | 'hvac' | 'gutters' | 'waterHeater' | 'garage' | 'fireplace'
  | 'dryer' | 'pool' | 'roof' | 'smokeDetectors' | 'lawn'
  | 'sumpPump' | 'irrigation' | 'deck' | 'waterSoftener'
  | 'generator' | 'septic';

export interface AgeAlert {
  years: number;
  msg: string;
  priority: 'critical' | 'high' | 'medium';
}

// Maps feature keys to the home profile DB column names
export const FEATURE_TO_DB_COLUMN: Record<FeatureKey, string> = {
  hvac: 'has_hvac',
  gutters: 'has_gutters',
  waterHeater: 'has_hvac', // water heater assumed with HVAC
  garage: 'has_garage',
  fireplace: 'has_fireplace',
  dryer: 'has_dryer',
  pool: 'has_pool',
  roof: 'has_roof',
  smokeDetectors: 'has_smoke_detectors',
  lawn: 'has_lawn',
  sumpPump: 'has_sump_pump',
  irrigation: 'has_irrigation',
  deck: 'has_deck',
  waterSoftener: 'has_water_softener',
  generator: 'has_generator',
  septic: 'has_septic',
};

export const FEATURE_TO_INSTALL_YEAR: Record<string, string> = {
  hvac: 'hvac_install_year',
  waterHeater: 'water_heater_install_year',
  roof: 'roof_install_year',
  garage: 'garage_door_install_year',
  fireplace: 'fireplace_install_year',
  pool: 'pool_install_year',
  sumpPump: 'sump_pump_install_year',
  septic: 'septic_install_year',
  smokeDetectors: 'smoke_detectors_install_year',
  irrigation: 'irrigation_install_year',
  dryer: 'dryer_install_year',
  deck: 'deck_install_year',
  waterSoftener: 'water_softener_install_year',
  generator: 'generator_install_year',
};

export const FEATURE_META: Record<FeatureKey, { name: string; emoji: string }> = {
  hvac: { name: 'HVAC System', emoji: '❄️' },
  gutters: { name: 'Gutters', emoji: '🏠' },
  waterHeater: { name: 'Water Heater', emoji: '🔥' },
  garage: { name: 'Garage', emoji: '🚗' },
  fireplace: { name: 'Fireplace', emoji: '🔥' },
  dryer: { name: 'Dryer', emoji: '👕' },
  pool: { name: 'Pool', emoji: '🏊' },
  roof: { name: 'Roof', emoji: '🏡' },
  smokeDetectors: { name: 'Smoke/CO Detectors', emoji: '🚨' },
  lawn: { name: 'Lawn & Landscaping', emoji: '🌿' },
  sumpPump: { name: 'Sump Pump', emoji: '💧' },
  irrigation: { name: 'Irrigation System', emoji: '🌧️' },
  deck: { name: 'Deck / Patio', emoji: '🪵' },
  waterSoftener: { name: 'Water Softener', emoji: '🚿' },
  generator: { name: 'Generator', emoji: '⚡' },
  septic: { name: 'Septic System', emoji: '🚰' },
};

export const CLIMATE_ZONES: Record<string, { name: string; icon: string; desc: string }> = {
  northeast: { name: 'Northeast', icon: '🍂', desc: 'Cold winters, warm summers' },
  southeast: { name: 'Southeast', icon: '🌴', desc: 'Mild winters, hot humid summers' },
  midwest: { name: 'Midwest', icon: '🌾', desc: 'Cold winters, hot summers' },
  southwest: { name: 'Southwest', icon: '🌵', desc: 'Mild winters, hot dry summers' },
  northwest: { name: 'Northwest', icon: '🌲', desc: 'Mild wet winters, cool summers' },
  mountain: { name: 'Mountain', icon: '⛰️', desc: 'Cold winters, dry summers' },
};

export const AGE_ALERTS: Record<string, AgeAlert[]> = {
  hvac: [
    { years: 15, msg: 'HVAC systems typically last 15–20 years. Start budgeting for replacement.', priority: 'high' },
    { years: 20, msg: 'Your HVAC is past expected lifespan. Replacement strongly recommended.', priority: 'critical' },
  ],
  waterHeater: [
    { years: 8, msg: 'Tank water heaters last 8–12 years. Watch for rust-colored water or leaks.', priority: 'medium' },
    { years: 12, msg: 'Your water heater is past typical lifespan. Failure risk is high.', priority: 'critical' },
  ],
  roof: [
    { years: 20, msg: 'Asphalt shingle roofs last 20–30 years. Schedule a professional inspection.', priority: 'high' },
    { years: 30, msg: 'Your roof is past expected lifespan. Prioritize replacement planning.', priority: 'critical' },
  ],
  smokeDetectors: [
    { years: 10, msg: 'Smoke detectors must be replaced every 10 years regardless of function.', priority: 'critical' },
  ],
  garage: [
    { years: 15, msg: 'Garage door openers and springs wear out around 15–20 years.', priority: 'medium' },
  ],
  sumpPump: [
    { years: 7, msg: 'Sump pumps last 7–10 years. Consider backup or replacement.', priority: 'high' },
  ],
  septic: [
    { years: 25, msg: 'Septic systems can last 25–30 years. Have a thorough professional assessment.', priority: 'high' },
  ],
  pool: [
    { years: 10, msg: 'Pool equipment (pump, filter, heater) typically needs replacement every 8–12 years.', priority: 'medium' },
  ],
  dryer: [
    { years: 13, msg: 'Dryers typically last 10–13 years. Watch for longer dry times or overheating.', priority: 'medium' },
  ],
  deck: [
    { years: 15, msg: 'Pressure-treated decks last 15–20 years. Inspect structural connections closely.', priority: 'high' },
  ],
};

// Maps recommendation categories to your existing task categories
export const CATEGORY_MAP: Record<string, string> = {
  maintenance: 'Appliances',
  seasonal: 'Exterior',
  safety: 'Interior',
};

// Override for specific features
export const FEATURE_CATEGORY_MAP: Record<string, string> = {
  hvac: 'HVAC',
  lawn: 'Yard',
  irrigation: 'Yard',
  roof: 'Exterior',
  gutters: 'Exterior',
  deck: 'Exterior',
  dryer: 'Appliances',
  waterHeater: 'Plumbing',
  waterSoftener: 'Plumbing',
  sumpPump: 'Plumbing',
  septic: 'Plumbing',
  fireplace: 'Interior',
  smokeDetectors: 'Interior',
  garage: 'Exterior',
  generator: 'Electrical',
  pool: 'Exterior',
};

export const ACTIONS: Recommendation[] = [
  // ─── JANUARY ────────────────────────────────────────────
  {
    id: 'hvac-filter-q1',
    feature: 'hvac',
    title: 'Replace HVAC air filters',
    desc: 'Swap filters every 60–90 days. Winter is peak heating usage — a clogged filter drives up costs and strains the system.',
    priority: 'high',
    category: 'maintenance',
    months: [0, 3, 6, 9],
    recurring: 'Every 3 months',
    recurrenceType: 'quarterly',
    timeEstMinutes: 15,
    costEstLow: 15,
    costEstHigh: 40,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'roof-ice-dams',
    feature: 'roof',
    title: 'Check for ice dam signs',
    desc: 'Look for icicles at roof edges, water stains on interior ceilings, or ice buildup in gutters. Address ventilation if recurring.',
    priority: 'high',
    category: 'seasonal',
    months: [0, 1],
    recurring: 'Winter months',
    recurrenceType: 'yearly',
    timeEstMinutes: 15,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: ['northeast', 'midwest', 'mountain'],
  },
  {
    id: 'fireplace-ash-jan',
    feature: 'fireplace',
    title: 'Inspect firebox & clean ash',
    desc: 'Remove ash buildup when it exceeds 1 inch. Check for cracked firebricks or damaged damper.',
    priority: 'medium',
    category: 'maintenance',
    months: [0],
    recurring: 'Monthly during burn season',
    recurrenceType: 'monthly',
    timeEstMinutes: 20,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'smoke-test-jan',
    feature: 'smokeDetectors',
    title: 'Test all smoke & CO detectors',
    desc: 'Press test buttons on every unit. Replace batteries in non-sealed units. Replace any unit older than 10 years.',
    priority: 'critical',
    category: 'safety',
    months: [0, 6],
    recurring: 'Twice yearly',
    recurrenceType: 'custom',
    recurrenceDays: 182,
    timeEstMinutes: 20,
    costEstLow: 0,
    costEstHigh: 30,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'generator-run-jan',
    feature: 'generator',
    title: 'Run generator under load',
    desc: 'Start generator and run 15–20 min under load. Check oil level and fuel supply. Verify transfer switch.',
    priority: 'high',
    category: 'maintenance',
    months: [0, 4, 9],
    recurring: 'Every 4 months',
    recurrenceType: 'custom',
    recurrenceDays: 120,
    timeEstMinutes: 30,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },

  // ─── FEBRUARY ───────────────────────────────────────────
  {
    id: 'sump-pump-test-feb',
    feature: 'sumpPump',
    title: 'Test sump pump before spring thaw',
    desc: 'Pour a bucket of water into the pit. Pump should activate and clear water in seconds. Check discharge pipe for ice.',
    priority: 'high',
    category: 'safety',
    months: [1],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 15,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: ['northeast', 'midwest', 'mountain', 'northwest'],
  },
  {
    id: 'wh-tpr-valve',
    feature: 'waterHeater',
    title: 'Test temperature-pressure relief valve',
    desc: 'Lift the TPR valve lever briefly — water should flow freely and stop when released. A stuck valve is a safety hazard.',
    priority: 'high',
    category: 'safety',
    months: [1],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 5,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'hvac-registers',
    feature: 'hvac',
    title: 'Inspect & clean heat registers',
    desc: 'Vacuum dust from all supply and return registers. Ensure furniture isn\'t blocking airflow.',
    priority: 'low',
    category: 'maintenance',
    months: [1],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 30,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },

  // ─── MARCH ──────────────────────────────────────────────
  {
    id: 'gutters-spring',
    feature: 'gutters',
    title: 'Spring gutter cleanout',
    desc: 'Clear debris from winter. Check downspouts for blockages. Ensure water drains at least 4 feet from foundation.',
    priority: 'high',
    category: 'seasonal',
    months: [2],
    recurring: 'Twice yearly',
    recurrenceType: 'custom',
    recurrenceDays: 182,
    timeEstMinutes: 90,
    costEstLow: 0,
    costEstHigh: 150,
    diyPro: 'Either',
    zones: 'all',
  },
  {
    id: 'lawn-first-mow',
    feature: 'lawn',
    title: 'First mow & pre-emergent herbicide',
    desc: 'Mow at highest setting. Apply pre-emergent before soil temps hit 55°F consistently. Skip if overseeding.',
    priority: 'medium',
    category: 'seasonal',
    months: [2],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 150,
    costEstLow: 20,
    costEstHigh: 50,
    diyPro: 'DIY',
    zones: ['northeast', 'midwest', 'southeast'],
  },
  {
    id: 'dryer-vent-clean',
    feature: 'dryer',
    title: 'Deep clean dryer vent duct',
    desc: 'Disconnect and clean full vent run to exterior. Lint buildup is a top cause of house fires. Replace crushed flex duct.',
    priority: 'high',
    category: 'safety',
    months: [2],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 45,
    costEstLow: 0,
    costEstHigh: 100,
    diyPro: 'Either',
    zones: 'all',
  },
  {
    id: 'chimney-sweep',
    feature: 'fireplace',
    title: 'Schedule chimney inspection & sweep',
    desc: 'End of burn season — remove creosote buildup and have flue inspected. CSIA-certified sweep recommended.',
    priority: 'high',
    category: 'safety',
    months: [2],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 60,
    costEstLow: 150,
    costEstHigh: 300,
    diyPro: 'Pro',
    zones: 'all',
  },
  {
    id: 'mower-blades',
    feature: 'lawn',
    title: 'Sharpen mower blades',
    desc: 'Dull blades tear grass and invite disease. Sharpen or replace before heavy mowing season.',
    priority: 'low',
    category: 'maintenance',
    months: [2],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 30,
    costEstLow: 10,
    costEstHigh: 20,
    diyPro: 'DIY',
    zones: 'all',
  },

  // ─── APRIL ──────────────────────────────────────────────
  {
    id: 'hvac-ac-tuneup',
    feature: 'hvac',
    title: 'Schedule spring AC tune-up',
    desc: 'Professional service: refrigerant check, coil cleaning, electrical inspection, condensate drain flush.',
    priority: 'medium',
    category: 'maintenance',
    months: [3],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 60,
    costEstLow: 100,
    costEstHigh: 200,
    diyPro: 'Pro',
    zones: 'all',
  },
  {
    id: 'wh-flush',
    feature: 'waterHeater',
    title: 'Flush water heater tank',
    desc: 'Drain sediment buildup to improve efficiency and extend tank life. Check anode rod — replace if over 50% corroded.',
    priority: 'medium',
    category: 'maintenance',
    months: [3],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 40,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'roof-spring',
    feature: 'roof',
    title: 'Post-winter roof inspection',
    desc: 'Check for missing/damaged shingles, cracked flashing around vents and chimneys, sagging areas, and gutter separation.',
    priority: 'high',
    category: 'seasonal',
    months: [3],
    recurring: 'Twice yearly',
    recurrenceType: 'custom',
    recurrenceDays: 182,
    timeEstMinutes: 30,
    costEstLow: 0,
    costEstHigh: 200,
    diyPro: 'Either',
    zones: 'all',
  },
  {
    id: 'garage-lube-spring',
    feature: 'garage',
    title: 'Lubricate garage door & test safety',
    desc: 'Silicone lubricant on rollers, hinges, tracks. Test auto-reverse with a 2x4 on ground. Check photo-eye alignment.',
    priority: 'medium',
    category: 'maintenance',
    months: [3, 9],
    recurring: 'Twice yearly',
    recurrenceType: 'custom',
    recurrenceDays: 182,
    timeEstMinutes: 20,
    costEstLow: 5,
    costEstHigh: 10,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'deck-inspect',
    feature: 'deck',
    title: 'Inspect deck for winter damage',
    desc: 'Check for loose boards, popped nails, rot at ledger board connection, and wobbly railings.',
    priority: 'high',
    category: 'seasonal',
    months: [3],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 30,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'irrigation-activate',
    feature: 'irrigation',
    title: 'Activate irrigation system',
    desc: 'Slowly open main valve. Walk each zone checking for broken heads, misalignment, and leaks. Adjust timers.',
    priority: 'medium',
    category: 'seasonal',
    months: [3],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 60,
    costEstLow: 0,
    costEstHigh: 75,
    diyPro: 'Either',
    zones: ['northeast', 'midwest', 'mountain'],
  },
  {
    id: 'septic-inspect',
    feature: 'septic',
    title: 'Schedule septic tank inspection',
    desc: 'Have tank levels and scum/sludge layers measured. Pump if sludge exceeds 1/3. Check baffles and drain field.',
    priority: 'high',
    category: 'maintenance',
    months: [3],
    recurring: 'Every 3 years',
    recurrenceType: 'custom',
    recurrenceDays: 1095,
    timeEstMinutes: 60,
    costEstLow: 300,
    costEstHigh: 600,
    diyPro: 'Pro',
    zones: 'all',
  },
  {
    id: 'lawn-fertilize-spring',
    feature: 'lawn',
    title: 'Apply spring fertilizer',
    desc: 'Slow-release nitrogen fertilizer after the second mow. Soil test first if you haven\'t in 3 years.',
    priority: 'medium',
    category: 'seasonal',
    months: [3],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 60,
    costEstLow: 25,
    costEstHigh: 50,
    diyPro: 'DIY',
    zones: ['northeast', 'midwest', 'southeast', 'southwest'],
  },

  // ─── MAY ────────────────────────────────────────────────
  {
    id: 'pool-open-north',
    feature: 'pool',
    title: 'Open pool for the season',
    desc: 'Remove cover, reconnect pump & filter, shock treat water, balance chemicals (pH 7.2–7.6), run filtration 8+ hrs/day.',
    priority: 'high',
    category: 'seasonal',
    months: [4],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 210,
    costEstLow: 100,
    costEstHigh: 300,
    diyPro: 'Either',
    zones: ['northeast', 'midwest', 'mountain'],
  },
  {
    id: 'pool-open-south',
    feature: 'pool',
    title: 'Open pool for the season',
    desc: 'Remove cover, reconnect pump & filter, shock treat water, balance chemicals (pH 7.2–7.6), run filtration 8+ hrs/day.',
    priority: 'high',
    category: 'seasonal',
    months: [2],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 210,
    costEstLow: 100,
    costEstHigh: 300,
    diyPro: 'Either',
    zones: ['southeast', 'southwest'],
  },
  {
    id: 'deck-seal',
    feature: 'deck',
    title: 'Clean & seal deck',
    desc: 'Power wash or use deck cleaner. Let dry 48 hours. Apply penetrating sealant or stain before summer UV.',
    priority: 'medium',
    category: 'seasonal',
    months: [4],
    recurring: 'Every 2–3 years',
    recurrenceType: 'custom',
    recurrenceDays: 912,
    timeEstMinutes: 300,
    costEstLow: 50,
    costEstHigh: 400,
    diyPro: 'Either',
    zones: 'all',
  },
  {
    id: 'hvac-condenser-clear',
    feature: 'hvac',
    title: 'Clear debris around AC condenser',
    desc: 'Remove leaves, grass clippings, and vegetation within 2 feet. Gently rinse coils with garden hose.',
    priority: 'medium',
    category: 'maintenance',
    months: [4],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 20,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'water-softener-clean',
    feature: 'waterSoftener',
    title: 'Clean brine tank & check salt',
    desc: 'Check for salt bridges or mushing. Break up solid masses. Clean tank interior. Top off salt.',
    priority: 'low',
    category: 'maintenance',
    months: [4, 10],
    recurring: 'Twice yearly',
    recurrenceType: 'custom',
    recurrenceDays: 182,
    timeEstMinutes: 30,
    costEstLow: 5,
    costEstHigh: 15,
    diyPro: 'DIY',
    zones: 'all',
  },

  // ─── JUNE ───────────────────────────────────────────────
  {
    id: 'lawn-summer-height',
    feature: 'lawn',
    title: 'Adjust mowing height for summer',
    desc: 'Raise mower to 3–4 inches. Taller grass shades roots, retains moisture, and crowds out weeds.',
    priority: 'low',
    category: 'seasonal',
    months: [5],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 5,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'irrigation-audit',
    feature: 'irrigation',
    title: 'Audit irrigation efficiency',
    desc: 'Place catch cups across each zone. Run 15 min, measure coverage. Adjust heads for even distribution.',
    priority: 'medium',
    category: 'maintenance',
    months: [5],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 90,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'pool-midseason',
    feature: 'pool',
    title: 'Mid-season pool equipment check',
    desc: 'Inspect pump basket, backwash filter, check water level, test chemical balance. Look for leaks.',
    priority: 'medium',
    category: 'maintenance',
    months: [5],
    recurring: 'Monthly in season',
    recurrenceType: 'monthly',
    timeEstMinutes: 30,
    costEstLow: 20,
    costEstHigh: 40,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'garage-clean-summer',
    feature: 'garage',
    title: 'Clean and organize garage',
    desc: 'Declutter, sweep, check for pest entry points. Inspect weatherstripping on garage door bottom seal.',
    priority: 'low',
    category: 'seasonal',
    months: [5],
    recurring: 'Twice yearly',
    recurrenceType: 'custom',
    recurrenceDays: 182,
    timeEstMinutes: 150,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },

  // ─── JULY ───────────────────────────────────────────────
  {
    id: 'hvac-midsummer',
    feature: 'hvac',
    title: 'Mid-summer HVAC check',
    desc: 'Replace filter if due. Check thermostat accuracy. Flush condensate drain with vinegar if slow.',
    priority: 'medium',
    category: 'maintenance',
    months: [6],
    recurring: 'Seasonal',
    recurrenceType: 'yearly',
    timeEstMinutes: 20,
    costEstLow: 15,
    costEstHigh: 40,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'roof-attic-vent',
    feature: 'roof',
    title: 'Check attic ventilation & temperature',
    desc: 'Attic should be within 10–15°F of outside temp. Poor ventilation accelerates shingle aging.',
    priority: 'medium',
    category: 'maintenance',
    months: [6],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 15,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'lawn-deep-water',
    feature: 'lawn',
    title: 'Deep water & spot-treat weeds',
    desc: 'Water deeply 2–3x/week rather than daily. Spot-treat broadleaf weeds — avoid full-lawn herbicide in heat.',
    priority: 'low',
    category: 'seasonal',
    months: [6],
    recurring: 'Weekly in summer',
    recurrenceType: 'custom',
    recurrenceDays: 7,
    timeEstMinutes: 30,
    costEstLow: 10,
    costEstHigh: 20,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'sump-pump-storm',
    feature: 'sumpPump',
    title: 'Test sump pump (storm season)',
    desc: 'Heavy rain season — verify pump activates. Check backup battery. Clear discharge area.',
    priority: 'high',
    category: 'safety',
    months: [6],
    recurring: 'Seasonal',
    recurrenceType: 'yearly',
    timeEstMinutes: 10,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: ['northeast', 'midwest', 'southeast'],
  },

  // ─── AUGUST ─────────────────────────────────────────────
  {
    id: 'hvac-fall-schedule',
    feature: 'hvac',
    title: 'Schedule fall furnace tune-up',
    desc: 'Book now — HVAC pros fill up fast in September. Check humidifier pads if equipped.',
    priority: 'medium',
    category: 'maintenance',
    months: [7],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 10,
    costEstLow: 100,
    costEstHigh: 200,
    diyPro: 'Pro',
    zones: ['northeast', 'midwest', 'mountain'],
  },
  {
    id: 'lawn-overseed-plan',
    feature: 'lawn',
    title: 'Plan fall overseeding & aeration',
    desc: 'Order seed now. Best window is 6–8 weeks before first frost. Core aeration before seeding gives best results.',
    priority: 'medium',
    category: 'seasonal',
    months: [7],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 15,
    costEstLow: 50,
    costEstHigh: 200,
    diyPro: 'Either',
    zones: ['northeast', 'midwest'],
  },
  {
    id: 'dryer-drum-clean',
    feature: 'dryer',
    title: 'Clean dryer drum & exterior vent flap',
    desc: 'Wipe interior drum with vinegar. Check exterior vent flap opens/closes freely — pest entry point if stuck.',
    priority: 'low',
    category: 'maintenance',
    months: [7],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 20,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },

  // ─── SEPTEMBER ──────────────────────────────────────────
  {
    id: 'lawn-aerate-overseed',
    feature: 'lawn',
    title: 'Aerate & overseed lawn',
    desc: 'Core aerate compacted areas. Overseed with appropriate grass type. Keep seed moist 2–3 weeks.',
    priority: 'high',
    category: 'seasonal',
    months: [8],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 240,
    costEstLow: 50,
    costEstHigh: 300,
    diyPro: 'Either',
    zones: ['northeast', 'midwest'],
  },
  {
    id: 'hvac-furnace-tuneup',
    feature: 'hvac',
    title: 'Furnace tune-up',
    desc: 'Professional inspection: heat exchanger, burner cleaning, safety controls, carbon monoxide check.',
    priority: 'high',
    category: 'safety',
    months: [8],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 60,
    costEstLow: 100,
    costEstHigh: 200,
    diyPro: 'Pro',
    zones: 'all',
  },
  {
    id: 'pool-close',
    feature: 'pool',
    title: 'Close pool for winter',
    desc: 'Balance chemicals, lower water level, blow out lines, add antifreeze to plumbing, install winter cover.',
    priority: 'high',
    category: 'seasonal',
    months: [8],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 240,
    costEstLow: 100,
    costEstHigh: 350,
    diyPro: 'Either',
    zones: ['northeast', 'midwest', 'mountain'],
  },
  {
    id: 'gutters-fall',
    feature: 'gutters',
    title: 'Fall gutter cleanout',
    desc: 'Clear leaf buildup before winter. Critical for preventing ice dams. Check slope toward downspouts.',
    priority: 'high',
    category: 'seasonal',
    months: [8],
    recurring: 'Twice yearly',
    recurrenceType: 'custom',
    recurrenceDays: 182,
    timeEstMinutes: 90,
    costEstLow: 0,
    costEstHigh: 150,
    diyPro: 'Either',
    zones: 'all',
  },

  // ─── OCTOBER ────────────────────────────────────────────
  {
    id: 'irrigation-winterize',
    feature: 'irrigation',
    title: 'Winterize irrigation system',
    desc: 'Blow out lines with compressed air. Shut off supply. Drain backflow preventer. Insulate exposed pipes.',
    priority: 'high',
    category: 'seasonal',
    months: [9],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 60,
    costEstLow: 0,
    costEstHigh: 75,
    diyPro: 'Either',
    zones: ['northeast', 'midwest', 'mountain'],
  },
  {
    id: 'fireplace-preseason',
    feature: 'fireplace',
    title: 'Pre-season fireplace check',
    desc: 'Open damper, check for obstructions, inspect firebox. Ensure chimney cap is secure. Stock firewood away from house.',
    priority: 'medium',
    category: 'seasonal',
    months: [9],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 15,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'roof-fall',
    feature: 'roof',
    title: 'Fall roof inspection',
    desc: 'Check flashing, vents, and shingles before winter. Clear debris. Look for moss or algae growth.',
    priority: 'high',
    category: 'seasonal',
    months: [9],
    recurring: 'Twice yearly',
    recurrenceType: 'custom',
    recurrenceDays: 182,
    timeEstMinutes: 30,
    costEstLow: 0,
    costEstHigh: 200,
    diyPro: 'Either',
    zones: 'all',
  },
  {
    id: 'wh-winter-check',
    feature: 'waterHeater',
    title: 'Check water heater before winter demand',
    desc: 'Inspect for leaks, listen for rumbling (sediment), check pilot/igniter. Set temp to 120°F.',
    priority: 'medium',
    category: 'maintenance',
    months: [9],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 10,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'generator-winter-service',
    feature: 'generator',
    title: 'Pre-winter generator service',
    desc: 'Change oil, replace air filter, test transfer switch, verify fuel supply. Run under full load 20 min.',
    priority: 'high',
    category: 'safety',
    months: [9],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 45,
    costEstLow: 50,
    costEstHigh: 200,
    diyPro: 'Either',
    zones: 'all',
  },

  // ─── NOVEMBER ───────────────────────────────────────────
  {
    id: 'gutters-final',
    feature: 'gutters',
    title: 'Final gutter check before freeze',
    desc: 'One last clearing after leaf drop peaks. Ensure downspout extensions direct water away from foundation.',
    priority: 'high',
    category: 'seasonal',
    months: [10],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 60,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: ['northeast', 'midwest', 'mountain'],
  },
  {
    id: 'hvac-seal-drafts',
    feature: 'hvac',
    title: 'Seal drafts & check weatherstripping',
    desc: 'Inspect doors and windows for air leaks. Replace worn weatherstripping. Caulk gaps around exterior penetrations.',
    priority: 'medium',
    category: 'seasonal',
    months: [10],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 90,
    costEstLow: 10,
    costEstHigh: 30,
    diyPro: 'DIY',
    zones: ['northeast', 'midwest', 'mountain', 'northwest'],
  },
  {
    id: 'sump-pump-winterize',
    feature: 'sumpPump',
    title: 'Winterize sump pump discharge',
    desc: 'Protect above-ground discharge from freezing. Ensure check valve works. Test backup power.',
    priority: 'high',
    category: 'safety',
    months: [10],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 15,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: ['northeast', 'midwest', 'mountain'],
  },
  {
    id: 'water-softener-nov',
    feature: 'waterSoftener',
    title: 'Check salt level & clean injector',
    desc: 'Top off salt before heavy holiday water use. Inspect brine injector for clogs. Run manual regeneration.',
    priority: 'low',
    category: 'maintenance',
    months: [10],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 15,
    costEstLow: 5,
    costEstHigh: 15,
    diyPro: 'DIY',
    zones: 'all',
  },

  // ─── DECEMBER ───────────────────────────────────────────
  {
    id: 'smoke-holiday',
    feature: 'smokeDetectors',
    title: 'Test detectors — holiday season',
    desc: 'Cooking and candle use peaks. Confirm all detectors work. Place extinguisher in kitchen. Review escape plan.',
    priority: 'critical',
    category: 'safety',
    months: [11],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 15,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'fireplace-mid-season',
    feature: 'fireplace',
    title: 'Mid-season firebox maintenance',
    desc: 'Remove excess ash. Inspect glass doors for cracks. Ensure damper seals tight when closed.',
    priority: 'low',
    category: 'maintenance',
    months: [11],
    recurring: 'During burn season',
    recurrenceType: 'yearly',
    timeEstMinutes: 15,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
  {
    id: 'roof-storm-monitor',
    feature: 'roof',
    title: 'Monitor roof after storms',
    desc: 'After heavy snow or wind, check for visible damage from ground. Clear gutters if ice is backing up.',
    priority: 'medium',
    category: 'seasonal',
    months: [11],
    recurring: 'As needed',
    recurrenceType: 'yearly',
    timeEstMinutes: 10,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: ['northeast', 'midwest', 'mountain'],
  },
  {
    id: 'hvac-yearend',
    feature: 'hvac',
    title: 'Year-end system review',
    desc: 'Review energy bills for spikes. Note repairs needed. Budget for replacements approaching end-of-life.',
    priority: 'low',
    category: 'maintenance',
    months: [11],
    recurring: 'Annual',
    recurrenceType: 'yearly',
    timeEstMinutes: 30,
    costEstLow: 0,
    costEstHigh: 0,
    diyPro: 'DIY',
    zones: 'all',
  },
];

// ─── Helper functions ─────────────────────────────────────

export function getRecommendationsForMonth(
  month: number,
  activeFeatures: FeatureKey[],
  climateZone: string,
  dismissedIds: string[] = []
): Recommendation[] {
  const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 };

  return ACTIONS
    .filter((a) => {
      if (!activeFeatures.includes(a.feature)) return false;
      if (!a.months.includes(month)) return false;
      if (dismissedIds.includes(a.id)) return false;
      if (a.zones !== 'all' && !a.zones.includes(climateZone)) return false;
      return true;
    })
    .sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority]);
}

export function getAgeAlerts(
  features: Record<string, { active: boolean; installYear: number | null }>,
  currentYear: number = new Date().getFullYear()
): Array<{ feature: string; featureName: string; emoji: string; age: number; msg: string; priority: string }> {
  const alerts: Array<{ feature: string; featureName: string; emoji: string; age: number; msg: string; priority: string }> = [];

  Object.entries(features).forEach(([key, feat]) => {
    if (!feat.active || !feat.installYear) return;
    const age = currentYear - feat.installYear;
    const featureAlerts = AGE_ALERTS[key] || [];
    const meta = FEATURE_META[key as FeatureKey];
    if (!meta) return;

    featureAlerts.forEach((a) => {
      if (age >= a.years) {
        alerts.push({
          feature: key,
          featureName: meta.name,
          emoji: meta.emoji,
          age,
          msg: a.msg,
          priority: a.priority,
        });
      }
    });
  });

  return alerts;
}

export function buildTaskFromRecommendation(rec: Recommendation) {
  const category = FEATURE_CATEGORY_MAP[rec.feature] || CATEGORY_MAP[rec.category] || 'Exterior';

  // Calculate due date — set to 7 days from now for this month's tasks
  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + 7);

  return {
    name: rec.title,
    category,
    due_date: dueDate.toISOString().split('T')[0],
    recurrence: rec.recurrenceType,
    recurrence_days: rec.recurrenceDays || null,
    notes: `${rec.desc}\n\nEstimated cost: $${rec.costEstLow}${rec.costEstHigh > rec.costEstLow ? '–$' + rec.costEstHigh : ''} | ${rec.diyPro} | ${rec.recurring}`,
    estimated_time: rec.timeEstMinutes,
    estimated_cost: rec.costEstHigh > 0 ? rec.costEstHigh : null,
    priority: rec.priority === 'critical' ? 1 : rec.priority === 'high' ? 2 : rec.priority === 'medium' ? 3 : 4,
  };
}
